[tool.poetry]
name = "obsidian-helper"
version = "0.1.0"
description = ""
authors = ["Tim Koval <timkoval00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
